<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260821074558 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Ajoute les blocages temporaires, la traçabilité des annulations/notifications et les documents multiples.';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE blocage_place (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, jeton VARCHAR(64) NOT NULL, nombre_places INT NOT NULL, phase VARCHAR(255) NOT NULL, cree_le TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, expire_le TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, sortie_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_B22094662CF647B ON blocage_place (jeton)');
        $this->addSql('CREATE INDEX IDX_B2209466CC72D953 ON blocage_place (sortie_id)');
        $this->addSql('CREATE INDEX idx_blocage_expiration ON blocage_place (expire_le)');
        $this->addSql('CREATE TABLE reservation_document (reservation_id INT NOT NULL, document_id INT NOT NULL, PRIMARY KEY (reservation_id, document_id))');
        $this->addSql('CREATE INDEX IDX_45DC6862B83297E7 ON reservation_document (reservation_id)');
        $this->addSql('CREATE INDEX IDX_45DC6862C33F7837 ON reservation_document (document_id)');
        $this->addSql('ALTER TABLE blocage_place ADD CONSTRAINT FK_B2209466CC72D953 FOREIGN KEY (sortie_id) REFERENCES sortie (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE reservation_document ADD CONSTRAINT FK_45DC6862B83297E7 FOREIGN KEY (reservation_id) REFERENCES reservation (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE reservation_document ADD CONSTRAINT FK_45DC6862C33F7837 FOREIGN KEY (document_id) REFERENCES document (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE document ADD montant NUMERIC(10, 2) DEFAULT NULL');
        $this->addSql("ALTER TABLE notification ADD statut VARCHAR(255) DEFAULT 'envoyee' NOT NULL");
        $this->addSql('ALTER TABLE notification ALTER statut DROP DEFAULT');
        $this->addSql('ALTER TABLE notification ADD erreur VARCHAR(500) DEFAULT NULL');
        $this->addSql('ALTER TABLE reservation DROP CONSTRAINT fk_42c84955c33f7837');
        $this->addSql('DROP INDEX idx_42c84955c33f7837');
        $this->addSql('ALTER TABLE reservation ADD origine_annulation VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE reservation ADD choix_annulation VARCHAR(255) DEFAULT NULL');
        $this->addSql('INSERT INTO reservation_document (reservation_id, document_id) SELECT id, document_id FROM reservation WHERE document_id IS NOT NULL');
        $this->addSql('ALTER TABLE reservation DROP document_id');
        $this->addSql("ALTER TABLE utilisateur ADD langue VARCHAR(255) DEFAULT 'fr' NOT NULL");
        $this->addSql('ALTER TABLE utilisateur ALTER langue DROP DEFAULT');
        $this->addSql(<<<'SQL'
CREATE FUNCTION verifier_creneau_baleine() RETURNS trigger AS $$
BEGIN
    IF NEW.type = 'baleine' THEN
        PERFORM pg_advisory_xact_lock(hashtextextended(NEW.date::text || NEW.heure_depart::text, 0));
        IF EXISTS (SELECT 1 FROM sortie s WHERE s.type = 'baleine' AND s.date = NEW.date AND s.heure_depart = NEW.heure_depart AND s.id <> COALESCE(NEW.id, 0)) THEN
            RAISE EXCEPTION 'Une seule sortie baleine est autorisée par créneau.';
        END IF;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql
SQL);
        $this->addSql('CREATE TRIGGER trg_sortie_baleine_unique BEFORE INSERT OR UPDATE ON sortie FOR EACH ROW EXECUTE FUNCTION verifier_creneau_baleine()');
        $this->addSql(<<<'SQL'
CREATE FUNCTION verifier_tarif_unique() RETURNS trigger AS $$
BEGIN
    PERFORM pg_advisory_xact_lock(hashtextextended(NEW.type_sortie || COALESCE(NEW.categorie, '') || COALESCE(NEW.bateau_id::text, ''), 0));
    IF NEW.bateau_id IS NULL AND EXISTS (SELECT 1 FROM tarif t WHERE t.type_sortie = NEW.type_sortie AND t.categorie = NEW.categorie AND t.bateau_id IS NULL AND t.id <> COALESCE(NEW.id, 0)) THEN
        RAISE EXCEPTION 'Un tarif collectif existe déjà pour ce type et cette catégorie.';
    END IF;
    IF NEW.categorie IS NULL AND EXISTS (SELECT 1 FROM tarif t WHERE t.type_sortie = NEW.type_sortie AND t.bateau_id = NEW.bateau_id AND t.categorie IS NULL AND t.id <> COALESCE(NEW.id, 0)) THEN
        RAISE EXCEPTION 'Un tarif de privatisation existe déjà pour ce bateau.';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql
SQL);
        $this->addSql('CREATE TRIGGER trg_tarif_unique BEFORE INSERT OR UPDATE ON tarif FOR EACH ROW EXECUTE FUNCTION verifier_tarif_unique()');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE blocage_place DROP CONSTRAINT FK_B2209466CC72D953');
        $this->addSql('ALTER TABLE reservation_document DROP CONSTRAINT FK_45DC6862B83297E7');
        $this->addSql('ALTER TABLE reservation_document DROP CONSTRAINT FK_45DC6862C33F7837');
        $this->addSql('DROP TABLE blocage_place');
        $this->addSql('ALTER TABLE document DROP montant');
        $this->addSql('ALTER TABLE notification DROP statut');
        $this->addSql('ALTER TABLE notification DROP erreur');
        $this->addSql('ALTER TABLE reservation ADD document_id INT DEFAULT NULL');
        $this->addSql('UPDATE reservation SET document_id = source.document_id FROM (SELECT reservation_id, MIN(document_id) AS document_id FROM reservation_document GROUP BY reservation_id) source WHERE reservation.id = source.reservation_id');
        $this->addSql('DROP TABLE reservation_document');
        $this->addSql('ALTER TABLE reservation DROP origine_annulation');
        $this->addSql('ALTER TABLE reservation DROP choix_annulation');
        $this->addSql('ALTER TABLE reservation ADD CONSTRAINT fk_42c84955c33f7837 FOREIGN KEY (document_id) REFERENCES document (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_42c84955c33f7837 ON reservation (document_id)');
        $this->addSql('ALTER TABLE utilisateur DROP langue');
        $this->addSql('DROP TRIGGER IF EXISTS trg_sortie_baleine_unique ON sortie');
        $this->addSql('DROP FUNCTION IF EXISTS verifier_creneau_baleine()');
        $this->addSql('DROP TRIGGER IF EXISTS trg_tarif_unique ON tarif');
        $this->addSql('DROP FUNCTION IF EXISTS verifier_tarif_unique()');
    }
}
